### ISSUE TITLE
Laravel 5.4 Compatibility

### ISSUE THREAD

**Issue by ghost** [jrm2k6/cloudder#27] opened 2017-01-31 17:27 UTC
2 errors on update:

```
Warning: Ambiguous class resolution, "Cloudinary\Akamai" was found in both "vendor/cloudinary/cloudinary_php/src/Akamai.php" and "vendor/cloudinary/cloudinary_php/src/Cloudinary/Akamai.php", the first will be used.
```

```
> post-update-cmd: php artisan optimize                           
  [Symfony\Component\Debug\Exception\FatalThrowableError]              
  Call to undefined method Illuminate\Foundation\Application::share()  
  Script php artisan optimize handling the post-update-cmd event returned with error code 1
```

**Comment by jrm2k6** [comment] 2017-01-31 17:35
@azcoppen Thanks! Will try to get to this tonight and will push a 5.4 branch if it is alright with you? I haven't had time to update my projects

**Comment by jrm2k6** [comment] 2017-01-31 17:39
@azcoppen for the warning, could it be because you pull the cloudinary_php library in your composer.json? It will be included by default when requiring cloudder, so maybe that can help!

**Comment by ghost** [comment] 2017-01-31 17:55
@jrm2k6 That would be fantastic chap, thank you! I forked it into a private repo. Can do a PR if you like.

The issue is Laravel 5.4 removes share() in the register() method of the service provider. You just need to change share() to singleton().

Edit: this might require more, as i'm getting "illegal offset type" with PHP7.1. Will need your update - will wait for it instead of using a fork as it's causing errors atm.

Edit: Also, am not requiring Cloudinary API in composer.

**Comment by ghost** [comment] 2017-01-31 17:57
See line 41:
https://github.com/fhmatch/cloudder-l54fork/blob/master/src/JD/Cloudder/CloudderServiceProvider.php

**Comment by ghost** [comment] 2017-01-31 18:08
Also, another error i'm getting here:

```
Warning: Ambiguous class resolution, "Cloudinary\Akamai" was found in both "vendor/cloudinary/cloudinary_php/src/Akamai.php" and "vendor/cloudinary/cloudinary_php/src/Cloudinary/Akamai.php", the first will be used.
```

**Comment by jrm2k6** [comment] 2017-01-31 18:17
Thanks for the hint, it should make my job easier. Will keep you up to date.

**Comment by ghost** [comment] 2017-01-31 18:22
@jrm2k6 It's an incredibly useful package - thanks for your work. Only 1 more thing - any chance you could change the Facade name to something more uniform than Cloudder? Would be great to just use Cloudinary::upload()!

**Comment by jrm2k6** [comment] 2017-01-31 19:31
I am not sure I can change the name as I am not affiliated with Cloudinary in any way. Not sure I can use that name.

**Comment by jrm2k6** [comment] 2017-02-01 04:23
@azcoppen @nicodebin Just pushed a new branch, could you guys check and make sure it works? Works fine on my local.

**Comment by ghost** [comment] 2017-02-01 19:17
@jrm2k6 works fine in Lumen 5.4, thanks! I've made a PR (#29) for an additional change that is also needed. Please be sure this works fine with Laravel 5.4

**Comment by jrm2k6** [comment] 2017-02-01 19:20
@nicodebin Just merged it, thanks for your PR. I will double check that maybe on my lunch break, and will merge/release if it works fine. It looks like it is backwards compatible so all good! Thanks for your patience. I still have most of my side projects running on Laravel 5.2. 🚒

**Comment by ghost** [comment] 2017-02-01 19:35
@jrm2k6 cool thanks! Yeah, me too.. most of my projects are running in 5.2 too, and a very huge one in 4.2 😱

**Comment by ghost** [comment] 2017-02-01 22:37
@jrm2k6 Testing later tonight - thanks so much for the speed you responded to the issue with!

**Comment by jrm2k6** [comment] 2017-02-02 17:09
@azcoppen let me know when it is confirmed, will try to release asap.

**Comment by ghost** [comment] 2017-02-03 17:51
@jrm2k6 Yep, looks great!

```
  - Removing jrm2k6/cloudder (dev-master 534cd8c)
  - Installing jrm2k6/cloudder (dev-master 64f4615) Downloading: 100% Extracting archive
```

**Closed as completed** 2017-02-03 17:52 UTC

**Comment by jrm2k6** [comment] 2017-02-03 17:59
Alright will release soon
